language: node_js
sudo: false
node_js:
  - "10"
  - "9"
  - "8"
env:
  CXX=g++-4.8
script:
  - npm run test-ci
install:
  - npm install
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
