os: Visual Studio 2017
version: "{build}"
platform: x64
environment:
  matrix:
  - nodejs_version: "12"
  - nodejs_version: "11"
  - nodejs_version: "10"
  - nodejs_version: "9"
  - nodejs_version: "8"
install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install -g npm@latest
  - npm install
test_script:
  - npm test
